### ISSUE TITLE
Power state switch should control Apple TV power state

### ISSUE THREAD

**Issue by NainRouge** [kurtwarwick-new/homebridge-appletv-now-playing#12]

**Comment by kurtwarwick-new** [comment]
Hi

I had never intended the switch to actually do anything. This project was simply to show now playing information, and the easiest way to get that into Homekit was via a switch. I will, however, be happy to add this as an enhancement.

I'll keep you posted.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi 

This has been completed, and according to my internal testing, is working as expected.

Please try it out and let me know how it goes.

Regards

Kurt

**Comment by sergoo-lbt** [comment]
> Hi
> 
> This has been completed, and according to my internal testing, is working as expected.
> 
> Please try it out and let me know how it goes.
> 
> Regards
> 
> Kurt

Still testing. But at the moment everything is fine! You are a wonderful person! Thanks!!!

**Comment by kurtwarwick-new** [comment]
Great to hear!

And thanks for the compliment.

I will close up this issue for now.

Regards

Kurt

**Comment by Frenkel85** [comment]
I am trying to wake my Apple TV from sleep via the switch of your plug-in but it doesn’t seem to work (anymore). I can wake the Apple TV via the TV accessory but in this way it also immediately selects an input/app. Would it be possible to just wake the Apple TV without selecting an input/app via this switch?
