### ISSUE TITLE
High processor load

### ISSUE THREAD

**Issue by another-ascii** [kurtwarwick-new/homebridge-appletv-now-playing#14]
First of all: thank you very much for the time and effort You have put into this. It is very much appreciated. I really appreciate being able to adjust lighting when starting something on the Apple TV

I have noticed that on my Raspberry Pi 4 the processor load seems to be relatively high compared to other plugins I have installed. CPU stats in Homebridge UI-X sees a typical 21% load with the plugin installed whereas it sits at about 3-4% w/o the plugin installed.

It is not of big concern but thought I'd ask if it is something you have noticed and if so - would have a look at eventually?

Again - thanks a lot for this plugin.

**Comment by kurtwarwick-new** [comment]
Hi @another-ascii 

Thanks for the kind words. It's refreshing to see that on Github these days. I'm just glad that my stuff is being used and enjoyed by others!

WRT the CPU, I can only assume it's the node-appletv-x package that would be doing this. I'm not 100% sure, nor am I 100% convinced that it is indeed that package. I will, therefore, do some investigating to see if I can find something, and if possible, fix it up.

Regards.

Kurt

**Comment by kurtwarwick-new** [comment]
Hi @another-ascii 

I have been looking into this and I cannot find anything that could cause this. In fact, while running on my homebridge server, I am only seeing load between 2 and 5 %. It never goes above that. That's with this plugin both installed and not (i.e. completely removed).

I am not sure what else to do since I am unable to replicate this on my end.

Are you running homebridge in a container or installed directly. Also, what hardware are you using?

My setup is on a RPi 4 with homebridge in a container.

Regards

Kurt

**Comment by another-ascii** [comment]
Hi Kurt,

thank you very much for looking into this.

Since I get this behaviour consistently I suspect that the cause may then be in an undesired interaction between the plugins I have installed? I will try to see if this has merit.

I am running on a RPi 4 4GB with homebridge installed directly.

Again - thank you very much for your time and effort.

Best regards.

**Comment by kurtwarwick-new** [comment]
Hey

I am sorry I couldn't help any further.  I did a little more troubleshooting, and the only time I could get the CPU to rise was when I quickly switched between apps and shows, forcing the nowPlaying event to emit. However, it only rose by 2%, pushing it to 7%. 

Have you tried the ol'turn it off and turn it on test? I.e. uninstall and re-install? Long shot, but it may be worth a try.

Regards

Kurt

**Comment by another-ascii** [comment]
I know you closed this but I just wanted to do a quick follow up: As of right now I see a 3% load (as opposed to the ~23% I previously reported). I have found no cause for the difference but I am confident the issue I have described and asked You about is not due to your plugin.

Thanks again for your time and effort and a great plugin.

Best regards.

**Comment by kurtwarwick-new** [comment]
Hi @another-ascii 

Thanks so much for getting back to me! I am happy to hear that you are seeing lower load. 

Hopefully it stays that way! 😄 

Kurt
