### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by adamrzanek** [kurtwarwick-new/homebridge-appletv-now-playing#17]
Is it possible to display Apple TV as TV accessory instead of a switch?

**Comment by kurtwarwick-new** [comment]
Hi @adamrzanek 

This is possible, but will require quite a bit of work. I will look into this and if I get time I will gladly make this change, since it's something I was considering in any case.

Regards

Kurt

**Comment by adamrzanek** [comment]
Great! Thank you!

**Comment by kurtwarwick-new** [comment]
Hi @adamrzanek 

I have started looking into this and it seems to be quite the challenge to have it be displayed as a TV. What I was hoping for was to list Apps as channels and have them launch that way, which would be super cool, but unfortunately, no one has found a way to do that as yet. What this means is that there will be a fairly useless, and empty, channels list under power button. Also, linking a proper volume control to the TV accessory doesn't seem entirely possible, so I'm going to need to look into that further. 

So, just letting you know I am trying this out, but I am also putting out a disclaimer of no promises! 

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi @adamrzanek 

After much trial and error, I have managed to get this working some-what. It does, however, seem futile as you are not actually able to run automatons based on a TV accessory state. Also, there is no way (at this time) to launch apps through node-appletv or node-appletv-x. This renders the input list useless, which means you end having just a massive power button and an empty box for an accessory. 

Given that I have done most of the work for this, I will leave it in and allow for the TV accessory to be added through config. 

I am hoping to merge this soon.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi again

I have just pushed out this change. Please remember that the TV Accessory is very limited and a current work in progress.

I have tried to overcome the app launch issue with button commands and app placement on the screen, but that is a work in progress and I recommend not trying it just yet.

Regards

Kurt
