### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by jaspercardol** [kurtwarwick-new/homebridge-appletv-now-playing#18]
Hi there,

This might be an isolated case but I thought I'd report it.

I pulled the plugin from NPM and installed it. While using the example configuration, homebridge reports two errors: 

1. The platform "AppleTvNowPlayingPlatform" is not registered by any plugin.

2. An unexpected "=" sign on line 15 in platform.js, specifically the one that in debug **=** message =>

**Comment by kurtwarwick-new** [comment]
Hi @jaspercardol 

This is very strange. May I ask that you paste the logs that has that error in here for more detail?

Also, I think no. 1 is happening due to no. 2, since no. 2 is preventing the plugin to load.

Could you also please let me know what version of Homebridge you are using, and are you HOOBS or any other non-vanilla version?

Thanks

Regards

Kurt

**Comment by jaspercardol** [comment]
Hi Kurt,

Thank you for your fast response. I'm running on an original raspberry pi B with vanilla homebridge. I was using 1.0.4 but just updated to 1.1.0. The issue still persists unfortunately.

I'm having some trouble finding this issue in my logs as they are no considered so far back that they have been cut off in the log (too old). I'll reinstall the plugin today to get the same messages and post them here.

**Comment by paulHasselkuss** [comment]
I have the same problem when using the plugin on an original Raspberry Pi B running Node v10.19.0. Could this be caused by using Node 10?

**Comment by jaspercardol** [comment]
Hi Paul,

That's an interesting question. I'm on node v11.15.0 on my pi but I also have a NAS running with docker support. I'm going to deploy a homebridge image on it and see if it has the same issue.

**Comment by kurtwarwick-new** [comment]
Hi @jaspercardol  and @paulHasselkuss 

Thanks for sending through more information. I think the issue is that Node < v12 does not support some of the syntax I am using. I will look at reverting some of that to support older versions.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi

I just wanted to send through an update on this; I am actively working on this issue and I am almost done with the re-factorization. I am hoping to merge the changes in soon. Please watch this space.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi

Please could you update your plugin with the latest changes? These should fix this issue.

Please let me know.

Regards

Kurt
