### ISSUE TITLE
Set HomeBridge accessory ID

### ISSUE THREAD

**Issue by johnlietzke** [kurtwarwick-new/homebridge-appletv-now-playing#2]
I am using the Homebridge-Alexa plugin with multiple Apple TV’s. The problem I am experiencing is duplicated IDs for the Apple TV.  Any chance a set ID could be added so they would each have a unique accessory I’d and name.

**Comment by kurtwarwick-new** [comment]
Hi @johnlietzke 

I do apologise for the delayed response. Given the global circumstances, I am sure you can understand.

Thanks for bringing this to my attention, and I will definitely look into it.

I will keep you updated on the progress.

Kurt

**Comment by kurtwarwick-new** [comment]
Hi @johnlietzke 

Could you clarify as to why you think Homebridge-Alexa could be clashing with this plugin? A debug output would be extremely helpful in solving this problem.

In my plugin, I create an accessory id using the Apple TVs actual UID. So there should be no way an accessory would clash with one from another plugin.

Regards

Kurt
