### ISSUE TITLE
Help with "retrieve credentials"

### ISSUE THREAD

**Issue by LordZork** [kurtwarwick-new/homebridge-appletv-now-playing#20]
Hi, would anyone be able to help me "**retrieve credentials**"?  I'm assuming the path given (in the code, below) needs to be edited, because when I run the command – as is – in terminal, it says "No such file or directory." 

"In order to retrieve credentials for your Apple TV, please follow these step

Execute the cli application bundled with this package from the package directory
`/path/to/homebridge-appletv-now-playing $ node .\bin\cli.js`"

/Edit: As of this writing, I'm running the latest **Homebridge** and **Homebridge Config UI X**, on the latest **Raspberry Pi 4**.  And, I'm fairly new to Homebridge – no idea how to find the correct path to use for the code (above).

**Comment by kurtwarwick-new** [comment]
Hi @LordZork 

Assuming you are not using Hoobs, you should be able to find the folder for the package in the _/homebridge/node_modules_.

If you open up terminal in Homebridge, you should be able to do the entire process there. 

![image](https://user-images.githubusercontent.com/61435184/86092988-924fca80-baae-11ea-9222-36cf2d893983.png)
![image](https://user-images.githubusercontent.com/61435184/86093043-a72c5e00-baae-11ea-9263-61bff9fac8fb.png)

Please let me know how that goes.

Regards

Kurt

**Comment by LordZork** [comment]
Hi @kurtwarwick-new 

Correct, I am not using HOOBs... just Homebridge.  That said, I still don't know how to get this to work...

Tried: 
`/homebridge/node_module/homebridge-appletv-now-playing $ node .\bin\cli.js`

Got: 
"No such file or directory"

Tried: 
`sudo /homebridge/node_module/homebridge-appletv-now-playing $ node .\bin\cli.js`

Got: 
"command not found."

Tried: sudo nano /homebridge/node_module/homebridge-appletv-now-playing $ node .\bin\cli.js

Got:
![Screen Shot 2020-06-30 at 12 58 21 PM](https://user-images.githubusercontent.com/65878888/86161078-5a5a7e80-bad2-11ea-9241-38f37a3e9c60.png)

Tried:
sudo nano /usr/local/lib/node_module/homebridge-appletv-now-playing $ node .\bin\cli.js

Got:
![Screen Shot 2020-06-30 at 12 56 03 PM](https://user-images.githubusercontent.com/65878888/86161137-69d9c780-bad2-11ea-94c8-16689dac2ec0.png)

Not sure if I'm on the right track, and – if so – what to do from here.

I am very new to this, so adding "sudo" or "sudo nano" or anything else needs to be spelled out, lol.

Any further help would be greatly appreciated, thanks!

**Comment by LordZork** [comment]
Also..

Tried:
`sudo nano /var/lib/homebridge/node_modules/homebridge-appletv-now-playing $ node .\bin\cli.js`

Got:
![Screen Shot 2020-06-30 at 1 44 27 PM](https://user-images.githubusercontent.com/65878888/86164764-e9b66080-bad7-11ea-8a28-6b39f79b0bc6.png)

Tried:
`sudo nano /var/lib/homebridge/homebridge-appletv-now-playing $ node .\bin\cli.js`

And...

`sudo nano /var/lib/homebridge-appletv-now-playing $ node .\bin\cli.js`

Got:
![Screen Shot 2020-06-30 at 1 41 37 PM](https://user-images.githubusercontent.com/65878888/86164822-00f54e00-bad8-11ea-9c4e-20d7d064e1b8.png)

Doesn't seem to matter if "/homebridge/" is in there, but it doesn't like "/node_modules/"... again, though, I still don't not know if I am on the right track or what to do from here...

**Comment by maxphour** [comment]
@LordZork Didn't got it to work with this plugin too. I installed node-appletv-x manually with "npm install -g node-appletv-x". After installation type "appletv pair" in the command line and follow the instructions shown.

**Comment by kurtwarwick-new** [comment]
Hi @LordZork 

I am not sure why you are unable to find the folder. Please see this GIF which shows what I was meaning with regards to the terminal in Homebridge. Hopefully this should help since the terminal in Homebridge opens in the Homebridge folder where node_modules should be found.

![apple-tv](https://user-images.githubusercontent.com/61435184/86172088-1c834780-bb1e-11ea-98fd-6e4503a7a1c0.gif)

Please let me know. Else, you could do what @maxphour did.

Regards

Kurt

**Comment by LordZork** [comment]
Hi @kurtwarwick-new 

This is what my terminal looks like...

![Screen Shot 2020-06-30 at 3 44 04 PM](https://user-images.githubusercontent.com/65878888/86175271-a44e5f00-bae8-11ea-99f4-8873d467e183.png)

I tried several variations:

`1s`, `# 1s`, `$ 1s`, `/homebridge # 1s`, `/homebridge $ 1s` and nothing worked.

**Comment by kurtwarwick-new** [comment]
Hey

Shucks, I have no idea how to help you further. I am not entirely clued up on where your setup may be installing the plugins. I am sorry that I am unable to assist any further.

I am looking into adding the credentials process to the configuration in homebridge-config-ui-x, but that seems like a very complicated process, so it won't be any time soon.

So sorry @LordZork 

Regards
 
Kurt

**Comment by LordZork** [comment]
Does this help?

![Screen Shot 2020-06-30 at 4 31 07 PM](https://user-images.githubusercontent.com/65878888/86179035-22156900-baef-11ea-91f7-a10eaef9681c.png)

**Comment by LordZork** [comment]
Hi @kurtwarwick-new 

I figured out the path/location/code...

`/usr/local/lib/node_modules/homebridge-appletv-now-playing/bin/cli.js`

I installed [**Homebridge**](https://github.com/homebridge/homebridge/wiki) on a **Raspberry Pi** via the [Official Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started).

For anyone else with the same setup, the path/code above will likely be the same.  You might want to add that path to your setup notes for the plugin.

**Comment by kurtwarwick-new** [comment]
@LordZork 

I am so pleased to hear that! I will certainly update the readme with that information. Thanks for letting me know BTW.

Regards

Kurt
