### ISSUE TITLE
Application Bundle Id's

### ISSUE THREAD

**Issue by bmonninkhof** [kurtwarwick-new/homebridge-appletv-now-playing#29]
What are the Bundle Id's?
Netflix com.netflix.Netflix
Youtube com.youtube.YouTube ???
Disney+ com.disneyplus.Disney+
etc?

**Comment by maxphour** [comment]
@bmonninkhof No, you have to download a third party home app, like Eve or Home+4. If you tap on the exposed tv switch in one of these apps you can see the Bundle ID's as a custom characteristic. So, play something in the YouTube App on your Apple TV, open the Eve or Home+ App and there you can see your Bundle ID for the currently running app.

**Comment by kurtwarwick-new** [comment]
Hi @bmonninkhof 

Unfortunately, I don't know them all. You can find the default apps [here]:(https://emm.how/t/ios-13-list-of-default-apps-and-bundle-id-s/1141).

The ones I do know so far are

Netflix : *com.netflix.Netflix*
Hulu : *com.hulu.plus*
CBS All Access : *com.disney.disneyplus*

Hope that helps.

Regards

Kurt
