### ISSUE TITLE
How to get credentials?

### ISSUE THREAD

**Issue by danielhelmstedt** [kurtwarwick-new/homebridge-appletv-now-playing#3]
Logs state No device has been configured. When I add the default config, logs say Found 2 Apple TV’s, but immediately SIGTERMs.

**Comment by StefanGebhardt** [comment]
Same question for me: nothing to find in the documentation...

**Comment by danielhelmstedt** [comment]
FYI - I figured it out, but I also switched to https://github.com/lukasroegner/homebridge-apple-tv-remote. They both use node-appletv-x for the backend though. 
That’s installed as a node_module within this plugin, so grab a terminal and CD into the node-appletv-x folder and run the exec to scan/pair

**Comment by StefanGebhardt** [comment]
Good tip - thank you :-)

**Comment by kurtwarwick-new** [comment]
Hi @danielhelmstedt  and @StefanGebhardt 

I do apologise for the delayed response. Given the global circumstances, hopefully you can understand.

Could you confirm that the issue is a lack of guidance on how to obtain credentials? I would love to improve on this project as I know it was something missing in any other HomeBridge plugin for me and I am sure the same is true for others.

Thanks!

**Comment by NainRouge** [comment]
For me that is correct. I do not understand how to get credentials.

**Comment by NainRouge** [comment]
Figured this one out by reading node-appletv-x documentation, you should add it to yours.

**Comment by kurtwarwick-new** [comment]
Hi @NainRouge 

Thanks for your feedback. I will definitely add some steps to get the credentials. I will also most likely be adding a CLI version of the app where one could retrieve credentials by running a command line version of this app.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Hi 

I have added some documentation on how to do this in future. There is a new CLI application that one could use to retrieve credentials for an Apple TV on their network. Should make this process a bit easier.

Thanks

Kurt
