### ISSUE TITLE
Plugin crashing Homebridge

### ISSUE THREAD

**Issue by adamrzanek** [kurtwarwick-new/homebridge-appletv-now-playing#5]
Installing the plugin completely crushing my homebridge setup. I’ve inserted correct credentials and it doesn’t help.

**Comment by kurtwarwick-new** [comment]
Hi @adamrzanek 

Do you perhaps more information for me to investigate this further? Hopefully you have a log output for me to check out.

I do apologise for the delayed response BTW.  

Regards

K
